### ISSUE TITLE
Who is using the dependency library

### ISSUE THREAD

**Issue by qixinynan** [Qixinies/libloader#1]
Hello, I'm author of this project, I want know is there anybody are using this library? should I keep updating?

**Comment by 1536243623** [comment]
I am currently using your library. I am also using the Tauri framework. From the demo, it seems like the lifecycle of the loaded function is inside the function. How can I bind it to the manager in Tauri and use it?

**Comment by qixinynan** [comment]
> I am currently using your library. I am also using the Tauri framework. From the demo, it seems like the lifecycle of the loaded function is inside the function. How can I bind it to the manager in Tauri and use it?

@1536243623  Can you provide your code

**Comment by Wyatex** [comment]
I am studying how to load dynamic libraries under Windows, and I came across this library. After trying, it seems that it is not possible to load DLL files.

my code:

```rust
use libloader::{get_libfn, libloading};
fn main() {
    get_libfn!("c_share_lib.dll", "hello", hello, ());
    hello();
}
```

panic:

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GetProcAddress { source: Os { code: 127, kind: Uncategorized, message: "找不到指定的程序。" } }', src\main.rs:3:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\result.rs:1651
   3: alloc::alloc::box_free
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\learn1.exe` (exit code: 101)
```

I have placed the "c_share_lib.dll" file in the system directory "C:\Windows\System32" and the project directory, but it seems that the error message is that the dynamic link library cannot be found.

If using a static library, it is call the hello function successfully based on the `cc` and `libc` crate.

**Comment by qixinynan** [comment]
> I am studying how to load dynamic libraries under Windows, and I came across this library. After trying, it seems that it is not possible to load DLL files.
> 
> 
> 
> my code:
> 
> 
> 
> ```rust
> 
> use libloader::{get_libfn, libloading};
> 
> fn main() {
> 
>     get_libfn!("c_share_lib.dll", "hello", hello, ());
> 
>     hello();
> 
> }
> 
> ```
> 
> 
> 
> panic:
> 
> 
> 
> ```rust
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GetProcAddress { source: Os { code: 127, kind: Uncategorized, message: "找不到指定的程序。" } }', src\main.rs:3:5
> 
> stack backtrace:
> 
>    0: std::panicking::begin_panic_handler
> 
>              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
> 
>    1: core::panicking::panic_fmt
> 
>              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
> 
>    2: core::result::unwrap_failed
> 
>              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\result.rs:1651
> 
>    3: alloc::alloc::box_free
> 
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 
> error: process didn't exit successfully: `target\release\learn1.exe` (exit code: 101)
> 
> ```
> 
> 
> 
> I have placed the "c_share_lib.dll" file in the system directory "C:\Windows\System32" and the project directory, but it seems that the error message is that the dynamic link library cannot be found.
> 
> 
> 
> If using a static library, it is call the hello function successfully based on the `cc` and `libc` crate.

@Wyatex  try to put your dll file same with your the directory of your exe file

**Comment by Wyatex** [comment]
![image](https://github.com/qixinynan/libloader/assets/13297495/805cb25e-51a4-4247-bfeb-000eb856f868)

It seems that the problem persists.@qixinynan

**Comment by qixinynan** [comment]
> ![image](https://github.com/qixinynan/libloader/assets/13297495/805cb25e-51a4-4247-bfeb-000eb856f868)
> 
> 
> 
> It seems that the problem persists.@qixinynan

@Wyatex 都是中国人！加我晚上回家看一下吧！很开心有人能用的库，我誓死给你解决咯，不准出轨其它的库！微信：codesx
